#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

remote_dir=/var/www/downloads
script_name=tampermonkey
server=me

echo -e "${GREEN}[${script_name}] Copying files to remote...${NC}"
echo rsync --verbose --compress --no-times ./*.js "${remote_dir}/tampermonkey/"

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0
