#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

remote_dir=/var/www/downloads
script_name=tampermonkey
server=me

echo -e "${GREEN}[${script_name}] Bumping version...${NC}"
git diff --name-only --line-prefix="$(git rev-parse --show-toplevel)/" | grep js | xargs -I{} bump-version {}

git add .
git commit -m "Version bump - $(date '+%Y/%m/%d %H:%M')"
git push

echo -e "${GREEN}[${script_name}] Copying files to remote...${NC}"
rsync --verbose --compress --no-times ./*.js "${server}:${remote_dir}/tampermonkey/"

echo -e "${GREEN}[${script_name}] All done!${NC}"
exit 0
